apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-talend
spec:
  rules:
  - host: "localhost"
    http:
      paths:
      - pathType: Prefix
        path: "/jgeneratedata"
        backend:
          service:
            name: flask-service
            port:
              number: 5000
