apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000  # Port utilisé par le service dans le cluster
      targetPort: 5000  # Port sur lequel le conteneur de l'application écoute
  type: NodePort  # Type de service pour exposer l'application via un port sur chaque nœud du cluster
